# Test Environment Configuration
micronaut:
  application:
    name: order-service-test
  server:
    port: -1  # Random port for parallel test execution
  
# Logging configuration for tests
logger:
  levels:
    me.windy.demo.order: DEBUG
    io.micronaut: WARN
    root: WARN

# Data source configuration (H2 in-memory for tests)
datasources:
  default:
    url: jdbc:h2:mem:testDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    dialect: H2

# JPA/Hibernate configuration
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        show_sql: false

# Disable message broker in tests
messaging:
  broker:
    enabled: false

# Disable external inventory service in tests
inventory:
  service:
    enabled: false

